# Generated by Django 5.1 on 2024-08-20 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitores',
            old_name='marca2',
            new_name='marca',
        ),
    ]
