# Generated by Django 5.1 on 2024-09-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_coolers_ram_tarjetas_monitores_hercios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolers',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitores',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procesadores',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjetas',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
