# Generated by Django 5.1 on 2024-09-03 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_coolers_precio_monitores_precio_procesadores_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolers',
            name='modelo',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitores',
            name='modelo',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='modelo',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarjetas',
            name='modelo',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
