# Generated by Django 5.1 on 2024-09-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_coolers_imagen_monitores_imagen_ram_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cooler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.coolers')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.monitores')),
                ('procesador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.procesadores')),
                ('ram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.ram')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.tarjetas')),
            ],
        ),
    ]
