# Generated by Django 5.1 on 2024-09-06 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='cooler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.coolers'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.monitores'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='procesador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.procesadores'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='ram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.ram'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tarjeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.tarjetas'),
        ),
    ]
