from django.urls import path #Importamos path de django.
from App import views #Importamos las views de la aplicación (App).

# Create your views here.
urlpatterns = [
    path('inicio/', views.inicio, name='inicio'),
    path('buscar/', views.buscar),
    path('registrarse/', views.usuariosFormulario, name='Registrarse'),
    path('procesadores/lista', views.ProcesadorListView.as_view(), name='ListaProcesadores'),
    path('procesadores/agregar', views.ProcesadorCreateView.as_view(), name='AgregarProcesador'),
    path('procesadores/<pk>', views.ProcesadorDetailView.as_view(), name='DetalleProcesador'),
    path('procesadores/<pk>/editar', views.ProcesadorUpdateView.as_view(), name='EditarProcesador'),
    path('procesadores/<pk>/borrar', views.ProcesadorDeleteView.as_view(), name='BorrarProcesador'),
    path('monitores/lista', views.MonitorListView.as_view(), name='ListaMonitores'),
    path('monitores/agregar', views.MonitorCreateView.as_view(), name='AgregarMonitor'),
    path('monitores/<pk>', views.MonitorDetailView.as_view(), name='DetalleMonitor'),
    path('monitores/<pk>/editar', views.MonitorUpdateView.as_view(), name='EditarMonitor'),
    path('monitores/<pk>/borrar', views.MonitorDeleteView.as_view(), name='BorrarMonitor'),
    path('tarjetas/lista', views.TarjetaListView.as_view(), name='ListaTarjetas'),
    path('tarjetas/agregar', views.TarjetaCreateView.as_view(), name='AgregarTarjeta'),
    path('tarjetas/<pk>', views.TarjetaDetailView.as_view(), name='DetalleTarjeta'),
    path('tarjetas/<pk>/editar', views.TarjetaUpdateView.as_view(), name='EditarTarjeta'),
    path('tarjetas/<pk>/borrar', views.TarjetaDeleteView.as_view(), name='BorrarTarjeta'),
    path('coolers/lista', views.CoolerListView.as_view(), name='ListaCoolers'),
    path('coolers/agregar', views.CoolerCreateView.as_view(), name='AgregarCooler'),
    path('coolers/<pk>', views.CoolerDetailView.as_view(), name='DetalleCooler'),
    path('coolers/<pk>/editar', views.CoolerUpdateView.as_view(), name='EditarCooler'),
    path('coolers/<pk>/borrar', views.CoolerDeleteView.as_view(), name='BorrarCooler'),
    path('ram/lista', views.RamListView.as_view(), name='ListaRam'),
    path('ram/agregar', views.RamCreateView.as_view(), name='AgregarRam'),
    path('ram/<pk>', views.RamDetailView.as_view(), name='DetalleRam'),
    path('ram/<pk>/editar', views.RamUpdateView.as_view(), name='EditarRam'),
    path('ram/<pk>/borrar', views.RamDeleteView.as_view(), name='BorrarRam'),
    # path('agregarprocesador/', views.procesadorFormulario, name='AgregarProcesadores'),
    # path('agregarmonitor/', views.monitorFormulario, name='AgregarMonitores'),
    # path('agregartarjeta/', views.tarjetaFormulario, name='AgregarTarjetas'),
    # path('agregarcooler/', views.coolerFormulario, name='AgregarCoolers'),
    # path('agregarram/', views.ramFormulario, name='AgregarRam'),
    # path('eliminarprocesador/<procesador_modelo>/', views.eliminarProcesador, name='EliminarProcesador'),
    # path('eliminarmonitor/<monitor_modelo>/', views.eliminarMonitor, name='EliminarMonitor'),
    # path('eliminartarjeta/<tarjeta_modelo>/', views.eliminarTarjeta, name='EliminarTarjeta'),
    # path('eliminarcooler/<cooler_modelo>/', views.eliminarCooler, name='EliminarCooler'),
    # path('eliminarram/<ram_modelo>/', views.eliminarRam, name='EliminarRam'),
    # path('procesadores/', views.leerProcesadores, name='LeerProcesadores'),
    # path('monitores/', views.leerMonitores, name='LeerMonitores'),
    # path('tarjetas/', views.leerTarjetas, name='LeerTarjetas'),
    # path('coolers/', views.leerCoolers, name='LeerCoolers'),
    # path('ram/', views.leerRam, name='LeerRam'),
]